services:
  api:
    container_name: sos-rs-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    tty: true
    depends_on:
      - db
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/usr/app
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE_NAME}?schema=public
      - HOST=${HOST}
      - PORT=${PORT}
  db:
    container_name: sos-rs-db
    image: postgres
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}

