services:
  sos-rs-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - '4000:4000'

  nginx:
    image: nginx:latest
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - PORT=${PORT}
    command: >
      bash -c '
      envsubst < /tmp/nginx.conf > /etc/nginx/nginx.conf;
      nginx -g "daemon off;"
      '
    volumes:
      - ./nginx.conf:/tmp/nginx.conf