services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    tty: true
    depends_on:
      - db
    volumes:
      - .:/usr/app
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE_NAME}?schema=public
      - HOST=${HOST}
      - PORT=${PORT}

  db:
    image: postgres
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}

  nginx:
    image: nginx:latest
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - PORT=${PORT}
    command: >
      bash -c '
      envsubst < /tmp/nginx.dev.conf > /etc/nginx/nginx.conf;
      nginx -g "daemon off;"
      '
    volumes:
      - ./nginx.dev.conf:/tmp/nginx.dev.conf
