name: Create and publish a Docker image

# secrets necessarios:
  # DEV_AWS_ACCESS_KEY_ID
  # DEV_AWS_SECRET_ACCESS_KEY
  # PROD_AWS_ACCESS_KEY_ID
  # PROD_AWS_SECRET_ACCESS_KEY

on:
  push:
    branches: 
    - develop
    - main

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.sha }}

  # dev
  DEV_AWS_ACCESS_KEY_ID: 
  DEV_AWS_SECRET_ACCESS_KEY:
  DEV_BRANCH: develop
  DEV_AWS_REGION: sa-east-1
  DEV_ECS_CLUSTER: sos-rs-freetier-ec2_cluster
  DEV_ECS_SERVICE: sos-rs-freetier-backend
  DEV_ECS_CONTAINER_NAME: server
  DEV_ECS_TASK_DEFINITION: sos-rs-freetier-backend

  # prod
  PROD_AWS_ACCESS_KEY_ID:
  PROD_AWS_SECRET_ACCESS_KEY: 
  PROD_AWS_REGION: sa-east-1
  PROD_BRANCH: main
  PROD_REGION: sa-east-1
  PROD_ECS_CLUSTER: sos-rs-freetier-ec2_cluster
  PROD_ECS_SERVICE: sos-rs-freetier-backend
  PROD_ECS_CONTAINER_NAME: server
  PROD_ECS_TASK_DEFINITION: sos-rs-freetier-backend

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    outputs:
      container_image: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.0
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags:
            type=raw,value={{branch}}-{{sha}}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/deploy-ecs.yml
    needs: [build]
    permissions:
      packages: read
    with:
      DEV_AWS_REGION:  ${{ env.DEV_AWS_REGION }}
      DEV_ECS_CLUSTER: ${{ env.DEV_ECS_CLUSTER }}
      DEV_ECS_SERVICE:  ${{ env.DEV_ECS_SERVICE }}
      DEV_ECS_CONTAINER_NAME: ${{ env.DEV_ECS_CONTAINER_NAME }}
      DEV_ECS_TASK_DEFINITION: ${{ env.DEV_ECS_TASK_DEFINITION }}
    secrets:
      DEV_AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      DEV_AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-ecs.yml
    needs: [build]
    permissions:
      packages: read
    with:
      PROD_AWS_REGION:  ${{ env.PROD_AWS_REGION }}
      PROD_ECS_CLUSTER: ${{ env.PROD_ECS_CLUSTER }}
      PROD_ECS_SERVICE:  ${{ env.PROD_ECS_SERVICE }}
      PROD_ECS_CONTAINER_NAME: ${{ env.PROD_ECS_CONTAINER_NAME }}
      PROD_ECS_TASK_DEFINITION: ${{ env.PROD_ECS_TASK_DEFINITION }}
    secrets:
      PROD_AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      PROD_AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}

