name: Deploy to ECS

on:
  workflow_call:
    inputs:
      AWS_REGION: 
        required: true
      ECS_CLUSTER:
        required: true
      ECS_SERVICE: 
        required: true
      ECS_CONTAINER_NAME:
        required: true
      ECS_TASK_DEFINITION:
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy-ecs:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy image to ECS
        uses: ./.github/workflows/deploy-ecs.yml
        with:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Fetch task definition
        id: fetch-task-definition
        run: DEV|
          aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }} --query taskDefinition > task-definition.json

      - name: Update container image in task definition
        id: update-image
        uses: aws-actions/amazon-ecs-render-task-definition@v1.3.0
        with:
          task-definition: task-definition.json
          container-name: ${{ env.ECS_CONTAINER_NAME }}
          image: ${{ env.CONTAINER_IMAGE }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1.5.0
        with:
          task-definition: ${{ steps.update-image.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: false
          force-new-deployment: true

